local gamesToFilter = {
    "Bullet Soul Infinite Burst",
    "Bullet Soul",
    "BulletSoul",
    "Dodonpachi DaiFukkatsu Black Label",
    "DoDonPachi DaiFukkatsu Black Label",
    "Dodonpachi DaiOuJou Black Label Extra",
    "DoDonPachi SaiDaiOuJou",
    "DoDonPachi: DaiFukkatsu Black Label",
    "Dodonpachi: DaiFukkatsu Ver 1.5",
    "Dodonpachi: DaiOuJou - Black Label Extra",
    "Dodonpachi: DaiOuJou Black Label Extra",
    "DoDonPachi: Resurrection Ver 1.5",
    "DoDonPachi: Resurrection",
    "Dodonpachi: SaiDaiOuJou",
    "Dodonpachi:DaiFukkatsu",
    "Eschatos",
    "ESCHATOS",
    "EspGaluda II - Black Label",
    "Espgaluda II Black Label",
    "Espgaluda II: Black Label",
    "Ketsui: Kizuna Jigoku Tachi Extra",
    "Ketsui",
    "Mamoru-Kun",
    "Mamorukun Curse!",
    "Muchi Muchi Pork! / (Ibara II): Pink Sweets",
    "Muchi Muchi Pork! & Pink Sweets",
    "Mushihimesama Futari",
    "Mushihimesama HD",
    "Mushihimesama: Futari Version 1.5",
    "Mushihimesama",
    "Raiden Fighters Aces",
    "Raiden IV (JP)",
    "Raiden IV (NA)",
    "Raiden IV",
    "Shikigami No Shiro III",
    "Shooting 10th Anniversary",
    "Shooting 200X",
    "Shooting Love 200X",
    "Shooting Love, 200X",
    "Under Defeat HD (JP)",
    "Under Defeat HD: Deluxe Edition",
    "Under Defeat HD",
    "アンダーディフィート HD",
    "アンダーディフィートHD",
    "エスカトス",
    "エスプガルーダIIブラックレーベル",
    "エスプガルーダIIブラックレーベル",
    "ケツイ",
    "ケツイ~絆地獄たち~EXTRA",
    "シューティングラブ。10周年",
    "シューティングラブ。200X",
    "シューティングラブ。コレクション",
    "バレット ソウル インフィニットバースト",
    "バレット ソウル 弾魂",
    "バレット ソウル",
    "バレットソウル",
    "バレットソウルインフィニットバースト",
    "バレットソウル弾魂",
    "まもるクンは呪われてしまった!",
    "むちむちポーク！＆ピンクスゥイーツ",
    "むちむちポーク&ピンクスゥイーツ",
    "ライデンファイターズエイシズ",
    "ライデンファイターズエイシズ",
    "式神の城III",
    "式神の城III",
    "怒首領蜂大往生ブラックレーベルEXTRA",
    "怒首領蜂大往生ブラックレーベルEXTRA",
    "怒首領蜂大復活",
    "怒首領蜂大復活",
    "怒首領蜂大復活Ver.1.5",
    "怒首領蜂大復活ブラックレーベル",
    "怒首領蜂大復活ブラックレーベル",
    "怒首領蜂最大往生",
    "怒首領蜂最大往生",
    "虫姫さま",
    "虫姫さまふたり",
    "雷電IV",
    "雷電IV"
}

local function IsTateable(Content, collection)
    for _, str in ipairs(collection) do
        if string.find(string.lower(Content.Name), string.lower(str)) then
            return true
        end
    end
    return false
end

GameListFilterCategories.User["Tate"] = function(Content)
    return IsTateable(Content, gamesToFilter)
end
